-- pt_features, tier A (event-derived), stratum P, graduations 2025-03-20 .. 2025-03-31.
-- Generated by recon/gen_pt_features_tier_a.py. Public column names only; no owner wallets.
WITH comp AS (
  SELECT mint, evt_block_time AS ct
  FROM pumpdotfun_solana.pump_evt_completeevent
  WHERE evt_block_date BETWEEN DATE '2025-03-20' AND DATE '2025-03-31'),
pc AS (
  SELECT base_mint AS mint, pool, quote_mint, creator AS migrator, evt_block_time AS pt, evt_block_slot AS ps,
         row_number() OVER (PARTITION BY base_mint ORDER BY evt_block_time) AS rn
  FROM pumpdotfun_solana.pump_amm_evt_createpoolevent
  WHERE evt_block_date BETWEEN DATE '2025-03-20' AND DATE '2025-04-01'),
u AS (
  SELECT c.mint, p.pool, p.quote_mint, p.migrator, p.pt AS grad_time, p.ps AS grad_slot
  FROM comp c JOIN pc p ON p.mint = c.mint AND p.rn = 1 AND p.pt >= c.ct AND p.pt < c.ct + INTERVAL '1' DAY
  WHERE p.quote_mint = 'So11111111111111111111111111111111111111112'),
cr AS (
  SELECT mint, arbitrary(COALESCE(creator, "user")) AS creator, min(evt_block_time) AS create_time, arbitrary(token_program) AS token_program
  FROM pumpdotfun_solana.pump_evt_createevent
  WHERE evt_block_date BETWEEN DATE '2025-01-09' AND DATE '2025-03-31' AND mint IN (SELECT mint FROM u)
  GROUP BY 1),
ev AS (
  SELECT pool, evt_block_time AS t, evt_block_slot AS slot, 'buy' AS side, user AS w,
         CAST(pool_quote_token_reserves AS double) AS q, CAST(pool_base_token_reserves AS double) AS b,
         -- ix_name is NULL on every decoded buy event (buyevent_variant_probe.sql): gross is the larger
         -- of the two quote fields and net the smaller, whichever variant emitted the event
         greatest(CAST(quote_amount_in AS double), CAST(user_quote_amount_in AS double)) AS gross,
         least(CAST(quote_amount_in AS double), CAST(user_quote_amount_in AS double)) AS net,
         CAST(base_amount_out AS double) AS base_amt, CAST(lp_fee AS double) AS lp,
         CAST(protocol_fee AS double) AS prot, CAST(coin_creator_fee AS double) AS cre
  FROM pumpdotfun_solana.pump_amm_evt_buyevent
  WHERE evt_block_date BETWEEN DATE '2025-03-20' AND DATE '2025-04-09' AND pool IN (SELECT pool FROM u)
  UNION ALL
  SELECT pool, evt_block_time, evt_block_slot, 'sell', user,
         CAST(pool_quote_token_reserves AS double), CAST(pool_base_token_reserves AS double),
         CAST(quote_amount_out AS double), CAST(user_quote_amount_out AS double),
         CAST(base_amount_in AS double), CAST(lp_fee AS double), CAST(protocol_fee AS double), CAST(coin_creator_fee AS double)
  FROM pumpdotfun_solana.pump_amm_evt_sellevent
  WHERE evt_block_date BETWEEN DATE '2025-03-20' AND DATE '2025-04-09' AND pool IN (SELECT pool FROM u)),
e AS (
  SELECT u.mint, u.grad_time, u.grad_slot, u.migrator, cr.creator, ev.*,
         -- virtual quote reserve: a BOOST-init constant on pools born from 2026-07-21, 0 before
         -- (VALIDATION_1_6: 17,584,505,288 .. 17,584,506,258 lamports on every post-BOOST pool read)
         CASE WHEN u.grad_time >= TIMESTAMP '2026-07-21 00:00:00' THEN 17584505500e0 ELSE 0e0 END AS v,
         CASE WHEN ev.side = 'buy' THEN ev.q + ev.net + ev.lp ELSE ev.q - ev.gross + ev.lp END AS q_post,
         CASE WHEN ev.side = 'buy' THEN ev.b - ev.base_amt ELSE ev.b + ev.base_amt END AS b_post
  FROM ev JOIN u ON u.pool = ev.pool
  LEFT JOIN cr ON cr.mint = u.mint
  WHERE ev.t >= u.grad_time AND ev.t < u.grad_time + INTERVAL '8' DAY),
ep AS (
  SELECT *, (q + v) / NULLIF(b, 0) AS px_pre, (q_post + v) / NULLIF(b_post, 0) AS px_post FROM e),
snap AS (
  SELECT mint, grad_time,
    min_by(px_pre, t) AS px_grad, min_by(q, t) AS qres_grad,
    max_by(px_post, t) FILTER (WHERE t < grad_time + INTERVAL '15' MINUTE) AS px_g15,
    max_by(q_post,  t) FILTER (WHERE t < grad_time + INTERVAL '15' MINUTE) AS qres_g15,
    max_by(b_post,  t) FILTER (WHERE t < grad_time + INTERVAL '15' MINUTE) AS bres_g15,
    max(px_post) FILTER (WHERE t >= grad_time + INTERVAL '15' MINUTE AND t < grad_time + INTERVAL '7' DAY) AS peak_7d_g15,
    max(px_post) FILTER (WHERE t >= grad_time + INTERVAL '15' MINUTE AND t < grad_time + INTERVAL '15' MINUTE + INTERVAL '24' HOUR) AS peak_24h_g15,
    max_by(px_post, t) FILTER (WHERE t < grad_time + INTERVAL '60' MINUTE) AS px_g60,
    max_by(q_post,  t) FILTER (WHERE t < grad_time + INTERVAL '60' MINUTE) AS qres_g60,
    max_by(b_post,  t) FILTER (WHERE t < grad_time + INTERVAL '60' MINUTE) AS bres_g60,
    max(px_post) FILTER (WHERE t >= grad_time + INTERVAL '60' MINUTE AND t < grad_time + INTERVAL '7' DAY) AS peak_7d_g60,
    max(px_post) FILTER (WHERE t >= grad_time + INTERVAL '60' MINUTE AND t < grad_time + INTERVAL '60' MINUTE + INTERVAL '24' HOUR) AS peak_24h_g60,
    max_by(px_post, t) FILTER (WHERE t < grad_time + INTERVAL '240' MINUTE) AS px_g240,
    max_by(q_post,  t) FILTER (WHERE t < grad_time + INTERVAL '240' MINUTE) AS qres_g240,
    max_by(b_post,  t) FILTER (WHERE t < grad_time + INTERVAL '240' MINUTE) AS bres_g240,
    max(px_post) FILTER (WHERE t >= grad_time + INTERVAL '240' MINUTE AND t < grad_time + INTERVAL '7' DAY) AS peak_7d_g240,
    max(px_post) FILTER (WHERE t >= grad_time + INTERVAL '240' MINUTE AND t < grad_time + INTERVAL '240' MINUTE + INTERVAL '24' HOUR) AS peak_24h_g240,
    max_by(px_post, t) FILTER (WHERE t < grad_time + INTERVAL '1' HOUR) AS px_1h,
    max_by(q_post,  t) FILTER (WHERE t < grad_time + INTERVAL '1' HOUR) AS qres_1h,
    max_by(px_post, t) FILTER (WHERE t < grad_time + INTERVAL '4' HOUR) AS px_4h,
    max_by(q_post,  t) FILTER (WHERE t < grad_time + INTERVAL '4' HOUR) AS qres_4h,
    max_by(px_post, t) FILTER (WHERE t < grad_time + INTERVAL '24' HOUR) AS px_24h,
    max_by(q_post,  t) FILTER (WHERE t < grad_time + INTERVAL '24' HOUR) AS qres_24h,
    max_by(px_post, t) FILTER (WHERE t < grad_time + INTERVAL '7' DAY) AS px_7d,
    max_by(q_post,  t) FILTER (WHERE t < grad_time + INTERVAL '7' DAY) AS qres_7d,
    approx_percentile(1e4 * (gross - net) / gross, 0.5) FILTER (WHERE side = 'buy'  AND gross > 0 AND t < grad_time + INTERVAL '7' DAY) AS cb_p50,
    approx_percentile(1e4 * (gross - net) / gross, 0.5) FILTER (WHERE side = 'sell' AND gross > 0 AND t < grad_time + INTERVAL '7' DAY) AS cs_p50,
    approx_percentile(1e4 * cre / gross, 0.5) FILTER (WHERE gross > 0 AND t < grad_time + INTERVAL '7' DAY) AS cf_p50,
    approx_percentile(1e4 * (gross - net - lp - prot - coalesce(cre, 0)) / gross, 0.9) FILTER (WHERE gross > 0 AND t < grad_time + INTERVAL '7' DAY) AS rs_p90,
    count_if(t < grad_time + INTERVAL '7' DAY) AS n_7d,
    sum(gross) FILTER (WHERE t < grad_time + INTERVAL '7' DAY) AS qv_7d,
    bool_or(side = 'sell' AND t < grad_time + INTERVAL '30' MINUTE AND w <> migrator AND (creator IS NULL OR w <> creator)) AS c10
  FROM ep GROUP BY 1, 2),
dd AS (   -- max drawdown per G and window, via running max over the window
  SELECT mint, g, win, max(1 - px_post / runmax) AS mdd FROM (
    SELECT ep.mint, gw.g, gw.win, ep.px_post,
           max(ep.px_post) OVER (PARTITION BY ep.mint, gw.g, gw.win ORDER BY ep.t, ep.slot ROWS UNBOUNDED PRECEDING) AS runmax
    FROM ep CROSS JOIN (VALUES (15, '24h'), (60, '24h'), (240, '24h'), (15, '7d'), (60, '7d'), (240, '7d')) AS gw(g, win)
    WHERE ep.t >= ep.grad_time + gw.g * INTERVAL '1' MINUTE
      AND ep.t < CASE WHEN gw.win = '24h' THEN ep.grad_time + gw.g * INTERVAL '1' MINUTE + INTERVAL '24' HOUR
                      ELSE ep.grad_time + INTERVAL '7' DAY END
  ) x GROUP BY 1, 2, 3),
ddp AS (
  SELECT mint,
    max(mdd) FILTER (WHERE g = 15  AND win = '7d')  AS mdd_7d_g15,
    max(mdd) FILTER (WHERE g = 60  AND win = '7d')  AS mdd_7d_g60,
    max(mdd) FILTER (WHERE g = 240 AND win = '7d')  AS mdd_7d_g240,
    max(mdd) FILTER (WHERE g = 15  AND win = '24h') AS mdd_24h_g15,
    max(mdd) FILTER (WHERE g = 60  AND win = '24h') AS mdd_24h_g60,
    max(mdd) FILTER (WHERE g = 240 AND win = '24h') AS mdd_24h_g240
  FROM dd GROUP BY 1),
d24 AS (  -- c09a / c09b: first 24h volume and same-wallet round trips
  SELECT mint, sum(vol) / NULLIF(count(*), 0) / 1e9 AS c09a,
         sum(CASE WHEN has_b AND has_s THEN vol END) / NULLIF(sum(vol), 0) AS c09b
  FROM (SELECT mint, w, sum(gross) AS vol, bool_or(side = 'buy') AS has_b, bool_or(side = 'sell') AS has_s
        FROM ep WHERE t < grad_time + INTERVAL '24' HOUR GROUP BY 1, 2) GROUP BY 1),
org AS (  -- organic v1: not creator, not migrator, not a graduation-slot trader
  SELECT ep.mint, count(DISTINCT ep.w) AS org1_n_7d, date_diff('second', min(ep.grad_time), min(ep.t)) AS org1_t_s
  FROM ep
  WHERE ep.t < ep.grad_time + INTERVAL '7' DAY AND ep.w <> ep.migrator AND (ep.creator IS NULL OR ep.w <> ep.creator)
    AND NOT EXISTS (SELECT 1 FROM ep b WHERE b.mint = ep.mint AND b.slot = b.grad_slot AND b.w = ep.w)
  GROUP BY 1),
f AS (
  SELECT u.mint,
    CASE WHEN u.grad_time < TIMESTAMP '2026-07-21 00:00:00' THEN 'pre_boost' ELSE 'post_boost' END AS era,
    'P' AS stratum, 'complete_to_pool_1d' AS adm_src, false AS birth_proxy,
    CAST(u.grad_time AS date) BETWEEN DATE '2025-08-05' AND DATE '2025-08-11' AS degraded,
    u.pool, u.quote_mint, cr.token_program, cr.create_time, u.grad_time, u.grad_slot, cr.creator,
    CASE WHEN u.grad_time >= TIMESTAMP '2026-07-21 00:00:00' THEN 17584505500e0 ELSE 0e0 END AS vqr,
    s.px_grad, s.qres_grad,
    s.px_g15, s.px_g60, s.px_g240, s.qres_g15, s.qres_g60, s.qres_g240, s.bres_g15, s.bres_g60, s.bres_g240,
    s.px_1h, s.px_4h, s.px_24h, s.px_7d, s.qres_1h, s.qres_4h, s.qres_24h, s.qres_7d,
    s.peak_7d_g15, s.peak_7d_g60, s.peak_7d_g240, s.peak_24h_g15, s.peak_24h_g60, s.peak_24h_g240,
    d.mdd_7d_g15, d.mdd_7d_g60, d.mdd_7d_g240, d.mdd_24h_g15, d.mdd_24h_g60, d.mdd_24h_g240,
    v.c09a, v.c09b, s.c10, false AS adj_applied, o.org1_n_7d, o.org1_t_s,
    s.cb_p50, s.cs_p50, s.cf_p50, s.rs_p90,
    s.px_g15 / NULLIF(s.px_grad, 0) AS mk_g15, s.px_g60 / NULLIF(s.px_grad, 0) AS mk_g60, s.px_g240 / NULLIF(s.px_grad, 0) AS mk_g240,
    s.n_7d, s.qv_7d
  FROM u LEFT JOIN cr ON cr.mint = u.mint LEFT JOIN snap s ON s.mint = u.mint
  LEFT JOIN ddp d ON d.mint = u.mint LEFT JOIN d24 v ON v.mint = u.mint LEFT JOIN org o ON o.mint = u.mint)
SELECT
  f.mint,
  f.era,
  f.stratum,
  f.adm_src,
  f.birth_proxy,
  f.degraded,
  f.pool,
  f.quote_mint,
  f.token_program,
  f.create_time,
  f.grad_time,
  f.grad_slot,
  f.creator,
  f.vqr,
  f.px_grad,
  f.qres_grad,
  f.px_g15,
  f.px_g60,
  f.px_g240,
  f.qres_g15,
  f.qres_g60,
  f.qres_g240,
  f.bres_g15,
  f.bres_g60,
  f.bres_g240,
  f.px_1h,
  f.px_4h,
  f.px_24h,
  f.px_7d,
  f.qres_1h,
  f.qres_4h,
  f.qres_24h,
  f.qres_7d,
  f.peak_7d_g15,
  f.peak_7d_g60,
  f.peak_7d_g240,
  f.mdd_7d_g15,
  f.mdd_7d_g60,
  f.mdd_7d_g240,
  f.peak_24h_g15,
  f.peak_24h_g60,
  f.peak_24h_g240,
  f.mdd_24h_g15,
  f.mdd_24h_g60,
  f.mdd_24h_g240,
  CAST(NULL AS varchar) AS c01,
  CAST(NULL AS varchar) AS c02,
  CAST(NULL AS varchar) AS c03,
  CAST(NULL AS integer) AS c04,
  CAST(NULL AS varchar) AS c05,
  CAST(NULL AS double) AS c06_g15,
  CAST(NULL AS double) AS c06_g60,
  CAST(NULL AS double) AS c06_g240,
  CAST(NULL AS double) AS c07_g15,
  CAST(NULL AS double) AS c07_g60,
  CAST(NULL AS double) AS c07_g240,
  CAST(NULL AS integer) AS c07b,
  CAST(NULL AS varchar) AS c08,
  CAST(NULL AS varchar) AS c11,
  CAST(NULL AS array(varchar)) AS u_codes,
  f.c09a,
  f.c09b,
  f.c10,
  f.adj_applied,
  CAST(NULL AS integer) AS seta_n,
  CAST(NULL AS double) AS seta_hold_g240,
  CAST(NULL AS array(double)) AS seta_flow_d0_7,
  CAST(NULL AS double) AS seta_sf_7d,
  CAST(NULL AS integer) AS cluster_n,
  CAST(NULL AS varchar) AS cluster_src,
  CAST(NULL AS timestamp) AS cluster_t1,
  CAST(NULL AS double) AS cluster_px_t1,
  f.org1_n_7d,
  CAST(NULL AS integer) AS org2_n_7d,
  f.org1_t_s,
  CAST(NULL AS integer) AS org2_t_s,
  f.cb_p50,
  f.cs_p50,
  f.cf_p50,
  f.rs_p90,
  f.mk_g15,
  f.mk_g60,
  f.mk_g240,
  f.n_7d,
  f.qv_7d,
  CAST(NULL AS double) AS seta_lat_s,
  CAST(NULL AS varchar) AS blk,
  CAST(NULL AS integer) AS seta_actors,
  CAST(NULL AS integer) AS cluster_actors,
  CAST(NULL AS integer) AS org1_actors_7d,
  CAST(NULL AS integer) AS org2_actors_7d
FROM f