-- Price-path summary, graduations 2026-08-10 .. 2026-08-10. Descriptive; one row per entry lag.
-- pt_features, tier A (event-derived), stratum P, graduations 2026-08-10 .. 2026-08-10.
-- Generated by recon/gen_pt_features_tier_a.py. Public column names only; no owner wallets.
WITH comp AS (
  SELECT mint, evt_block_time AS ct
  FROM pumpdotfun_solana.pump_evt_completeevent
  WHERE evt_block_date BETWEEN DATE '2026-08-10' AND DATE '2026-08-10'),
pc AS (
  SELECT base_mint AS mint, pool, quote_mint, creator AS migrator, evt_block_time AS pt, evt_block_slot AS ps,
         row_number() OVER (PARTITION BY base_mint ORDER BY evt_block_time) AS rn
  FROM pumpdotfun_solana.pump_amm_evt_createpoolevent
  WHERE evt_block_date BETWEEN DATE '2026-08-10' AND DATE '2026-08-11'),
u AS (
  SELECT c.mint, p.pool, p.quote_mint, p.migrator, p.pt AS grad_time, p.ps AS grad_slot
  FROM comp c JOIN pc p ON p.mint = c.mint AND p.rn = 1 AND p.pt >= c.ct AND p.pt < c.ct + INTERVAL '1' DAY
  WHERE p.quote_mint = 'So11111111111111111111111111111111111111112'),
cr AS (
  SELECT mint, arbitrary(COALESCE(creator, "user")) AS creator, min(evt_block_time) AS create_time, arbitrary(token_program) AS token_program
  FROM pumpdotfun_solana.pump_evt_createevent
  WHERE evt_block_date BETWEEN DATE '2026-06-01' AND DATE '2026-08-10' AND mint IN (SELECT mint FROM u)
  GROUP BY 1),
ev AS (
  SELECT pool, evt_block_time AS t, evt_block_slot AS slot, 'buy' AS side, user AS w,
         CAST(pool_quote_token_reserves AS double) AS q, CAST(pool_base_token_reserves AS double) AS b,
         CASE WHEN ix_name = 'buy_exact_quote_in' THEN CAST(quote_amount_in AS double) ELSE CAST(user_quote_amount_in AS double) END AS gross,
         CASE WHEN ix_name = 'buy_exact_quote_in' THEN CAST(user_quote_amount_in AS double) ELSE CAST(quote_amount_in AS double) END AS net,
         CAST(base_amount_out AS double) AS base_amt, CAST(lp_fee AS double) AS lp,
         CAST(protocol_fee AS double) AS prot, CAST(coin_creator_fee AS double) AS cre
  FROM pumpdotfun_solana.pump_amm_evt_buyevent
  WHERE evt_block_date BETWEEN DATE '2026-08-10' AND DATE '2026-08-19' AND pool IN (SELECT pool FROM u)
  UNION ALL
  SELECT pool, evt_block_time, evt_block_slot, 'sell', user,
         CAST(pool_quote_token_reserves AS double), CAST(pool_base_token_reserves AS double),
         CAST(quote_amount_out AS double), CAST(user_quote_amount_out AS double),
         CAST(base_amount_in AS double), CAST(lp_fee AS double), CAST(protocol_fee AS double), CAST(coin_creator_fee AS double)
  FROM pumpdotfun_solana.pump_amm_evt_sellevent
  WHERE evt_block_date BETWEEN DATE '2026-08-10' AND DATE '2026-08-19' AND pool IN (SELECT pool FROM u)),
e AS (
  SELECT u.mint, u.grad_time, u.grad_slot, u.migrator, cr.creator, ev.*,
         -- virtual quote reserve: a BOOST-init constant on pools born from 2026-07-21, 0 before
         -- (VALIDATION_1_6: 17,584,505,288 .. 17,584,506,258 lamports on every post-BOOST pool read)
         CASE WHEN u.grad_time >= TIMESTAMP '2026-07-21 00:00:00' THEN 17584505500e0 ELSE 0e0 END AS v,
         CASE WHEN ev.side = 'buy' THEN ev.q + ev.net + ev.lp ELSE ev.q - ev.gross + ev.lp END AS q_post,
         CASE WHEN ev.side = 'buy' THEN ev.b - ev.base_amt ELSE ev.b + ev.base_amt END AS b_post
  FROM ev JOIN u ON u.pool = ev.pool
  LEFT JOIN cr ON cr.mint = u.mint
  WHERE ev.t >= u.grad_time AND ev.t < u.grad_time + INTERVAL '8' DAY),
ep AS (
  SELECT *, (q + v) / NULLIF(b, 0) AS px_pre, (q_post + v) / NULLIF(b_post, 0) AS px_post FROM e),
snap AS (
  SELECT mint, grad_time,
    min_by(px_pre, t) AS px_grad, min_by(q, t) AS qres_grad,
    max_by(px_post, t) FILTER (WHERE t < grad_time + INTERVAL '15' MINUTE) AS px_g15,
    max_by(q_post,  t) FILTER (WHERE t < grad_time + INTERVAL '15' MINUTE) AS qres_g15,
    max_by(b_post,  t) FILTER (WHERE t < grad_time + INTERVAL '15' MINUTE) AS bres_g15,
    max(px_post) FILTER (WHERE t >= grad_time + INTERVAL '15' MINUTE AND t < grad_time + INTERVAL '7' DAY) AS peak_7d_g15,
    max(px_post) FILTER (WHERE t >= grad_time + INTERVAL '15' MINUTE AND t < grad_time + INTERVAL '15' MINUTE + INTERVAL '24' HOUR) AS peak_24h_g15,
    max_by(px_post, t) FILTER (WHERE t < grad_time + INTERVAL '60' MINUTE) AS px_g60,
    max_by(q_post,  t) FILTER (WHERE t < grad_time + INTERVAL '60' MINUTE) AS qres_g60,
    max_by(b_post,  t) FILTER (WHERE t < grad_time + INTERVAL '60' MINUTE) AS bres_g60,
    max(px_post) FILTER (WHERE t >= grad_time + INTERVAL '60' MINUTE AND t < grad_time + INTERVAL '7' DAY) AS peak_7d_g60,
    max(px_post) FILTER (WHERE t >= grad_time + INTERVAL '60' MINUTE AND t < grad_time + INTERVAL '60' MINUTE + INTERVAL '24' HOUR) AS peak_24h_g60,
    max_by(px_post, t) FILTER (WHERE t < grad_time + INTERVAL '240' MINUTE) AS px_g240,
    max_by(q_post,  t) FILTER (WHERE t < grad_time + INTERVAL '240' MINUTE) AS qres_g240,
    max_by(b_post,  t) FILTER (WHERE t < grad_time + INTERVAL '240' MINUTE) AS bres_g240,
    max(px_post) FILTER (WHERE t >= grad_time + INTERVAL '240' MINUTE AND t < grad_time + INTERVAL '7' DAY) AS peak_7d_g240,
    max(px_post) FILTER (WHERE t >= grad_time + INTERVAL '240' MINUTE AND t < grad_time + INTERVAL '240' MINUTE + INTERVAL '24' HOUR) AS peak_24h_g240,
    max_by(px_post, t) FILTER (WHERE t < grad_time + INTERVAL '1' HOUR) AS px_1h,
    max_by(q_post,  t) FILTER (WHERE t < grad_time + INTERVAL '1' HOUR) AS qres_1h,
    max_by(px_post, t) FILTER (WHERE t < grad_time + INTERVAL '4' HOUR) AS px_4h,
    max_by(q_post,  t) FILTER (WHERE t < grad_time + INTERVAL '4' HOUR) AS qres_4h,
    max_by(px_post, t) FILTER (WHERE t < grad_time + INTERVAL '24' HOUR) AS px_24h,
    max_by(q_post,  t) FILTER (WHERE t < grad_time + INTERVAL '24' HOUR) AS qres_24h,
    max_by(px_post, t) FILTER (WHERE t < grad_time + INTERVAL '7' DAY) AS px_7d,
    max_by(q_post,  t) FILTER (WHERE t < grad_time + INTERVAL '7' DAY) AS qres_7d,
    approx_percentile(1e4 * (gross - net) / gross, 0.5) FILTER (WHERE side = 'buy'  AND gross > 0 AND t < grad_time + INTERVAL '7' DAY) AS cb_p50,
    approx_percentile(1e4 * (gross - net) / gross, 0.5) FILTER (WHERE side = 'sell' AND gross > 0 AND t < grad_time + INTERVAL '7' DAY) AS cs_p50,
    approx_percentile(1e4 * cre / gross, 0.5) FILTER (WHERE gross > 0 AND t < grad_time + INTERVAL '7' DAY) AS cf_p50,
    approx_percentile(1e4 * (gross - net - lp - prot - coalesce(cre, 0)) / gross, 0.9) FILTER (WHERE gross > 0 AND t < grad_time + INTERVAL '7' DAY) AS rs_p90,
    count_if(t < grad_time + INTERVAL '7' DAY) AS n_7d,
    sum(gross) FILTER (WHERE t < grad_time + INTERVAL '7' DAY) AS qv_7d,
    bool_or(side = 'sell' AND t < grad_time + INTERVAL '30' MINUTE AND w <> migrator AND (creator IS NULL OR w <> creator)) AS c10
  FROM ep GROUP BY 1, 2),
dd AS (   -- max drawdown per G and window, via running max over the window
  SELECT mint, g, win, max(1 - px_post / runmax) AS mdd FROM (
    SELECT ep.mint, gw.g, gw.win, ep.px_post,
           max(ep.px_post) OVER (PARTITION BY ep.mint, gw.g, gw.win ORDER BY ep.t, ep.slot ROWS UNBOUNDED PRECEDING) AS runmax
    FROM ep CROSS JOIN (VALUES (15, '24h'), (60, '24h'), (240, '24h'), (15, '7d'), (60, '7d'), (240, '7d')) AS gw(g, win)
    WHERE ep.t >= ep.grad_time + gw.g * INTERVAL '1' MINUTE
      AND ep.t < CASE WHEN gw.win = '24h' THEN ep.grad_time + gw.g * INTERVAL '1' MINUTE + INTERVAL '24' HOUR
                      ELSE ep.grad_time + INTERVAL '7' DAY END
  ) x GROUP BY 1, 2, 3),
ddp AS (
  SELECT mint,
    max(mdd) FILTER (WHERE g = 15  AND win = '7d')  AS mdd_7d_g15,
    max(mdd) FILTER (WHERE g = 60  AND win = '7d')  AS mdd_7d_g60,
    max(mdd) FILTER (WHERE g = 240 AND win = '7d')  AS mdd_7d_g240,
    max(mdd) FILTER (WHERE g = 15  AND win = '24h') AS mdd_24h_g15,
    max(mdd) FILTER (WHERE g = 60  AND win = '24h') AS mdd_24h_g60,
    max(mdd) FILTER (WHERE g = 240 AND win = '24h') AS mdd_24h_g240
  FROM dd GROUP BY 1)
  SELECT 15 AS lag_min, count(*) AS tokens, count(s.px_g15) AS has_entry, count(s.px_7d) AS has_7d,
    approx_percentile(s.px_7d / s.px_g15, ARRAY[0.1, 0.25, 0.5, 0.75, 0.9, 0.99]) AS ret7_pcts,
    avg(s.px_7d / s.px_g15) AS ret7_mean, avg(CASE WHEN s.px_7d > s.px_g15 THEN 1e0 ELSE 0e0 END) AS share_above_entry,
    approx_percentile(s.peak_7d_g15 / s.px_g15, 0.5) AS peak7_p50, avg(CASE WHEN s.peak_7d_g15 >= 2 * s.px_g15 THEN 1e0 ELSE 0e0 END) AS share_2x,
    approx_percentile(s.peak_24h_g15 / s.px_g15, 0.5) AS peak24_p50, approx_percentile(d.mdd_7d_g15, 0.5) AS mdd7_p50,
    approx_percentile(s.px_g15 / s.px_grad, 0.5) AS mk_p50,
    approx_percentile(s.cb_p50, 0.5) AS buy_cost_bps_p50, approx_percentile(s.cs_p50, 0.5) AS sell_cost_bps_p50,
    approx_percentile(s.qres_g15 / 1e9, 0.5) AS qres_sol_p50,
    count_if(s.peak_24h_g15 >= 3 * s.px_g15 AND s.px_7d >= s.px_g15) AS h5_winners,
    count_if(s.peak_24h_g15 >= 3 * s.px_g15) AS peak24_3x
  FROM snap s LEFT JOIN ddp d ON d.mint = s.mint WHERE s.px_g15 > 0
  UNION ALL
  SELECT 60 AS lag_min, count(*) AS tokens, count(s.px_g60) AS has_entry, count(s.px_7d) AS has_7d,
    approx_percentile(s.px_7d / s.px_g60, ARRAY[0.1, 0.25, 0.5, 0.75, 0.9, 0.99]) AS ret7_pcts,
    avg(s.px_7d / s.px_g60) AS ret7_mean, avg(CASE WHEN s.px_7d > s.px_g60 THEN 1e0 ELSE 0e0 END) AS share_above_entry,
    approx_percentile(s.peak_7d_g60 / s.px_g60, 0.5) AS peak7_p50, avg(CASE WHEN s.peak_7d_g60 >= 2 * s.px_g60 THEN 1e0 ELSE 0e0 END) AS share_2x,
    approx_percentile(s.peak_24h_g60 / s.px_g60, 0.5) AS peak24_p50, approx_percentile(d.mdd_7d_g60, 0.5) AS mdd7_p50,
    approx_percentile(s.px_g60 / s.px_grad, 0.5) AS mk_p50,
    approx_percentile(s.cb_p50, 0.5) AS buy_cost_bps_p50, approx_percentile(s.cs_p50, 0.5) AS sell_cost_bps_p50,
    approx_percentile(s.qres_g60 / 1e9, 0.5) AS qres_sol_p50,
    count_if(s.peak_24h_g60 >= 3 * s.px_g60 AND s.px_7d >= s.px_g60) AS h5_winners,
    count_if(s.peak_24h_g60 >= 3 * s.px_g60) AS peak24_3x
  FROM snap s LEFT JOIN ddp d ON d.mint = s.mint WHERE s.px_g60 > 0
  UNION ALL
  SELECT 240 AS lag_min, count(*) AS tokens, count(s.px_g240) AS has_entry, count(s.px_7d) AS has_7d,
    approx_percentile(s.px_7d / s.px_g240, ARRAY[0.1, 0.25, 0.5, 0.75, 0.9, 0.99]) AS ret7_pcts,
    avg(s.px_7d / s.px_g240) AS ret7_mean, avg(CASE WHEN s.px_7d > s.px_g240 THEN 1e0 ELSE 0e0 END) AS share_above_entry,
    approx_percentile(s.peak_7d_g240 / s.px_g240, 0.5) AS peak7_p50, avg(CASE WHEN s.peak_7d_g240 >= 2 * s.px_g240 THEN 1e0 ELSE 0e0 END) AS share_2x,
    approx_percentile(s.peak_24h_g240 / s.px_g240, 0.5) AS peak24_p50, approx_percentile(d.mdd_7d_g240, 0.5) AS mdd7_p50,
    approx_percentile(s.px_g240 / s.px_grad, 0.5) AS mk_p50,
    approx_percentile(s.cb_p50, 0.5) AS buy_cost_bps_p50, approx_percentile(s.cs_p50, 0.5) AS sell_cost_bps_p50,
    approx_percentile(s.qres_g240 / 1e9, 0.5) AS qres_sol_p50,
    count_if(s.peak_24h_g240 >= 3 * s.px_g240 AND s.px_7d >= s.px_g240) AS h5_winners,
    count_if(s.peak_24h_g240 >= 3 * s.px_g240) AS peak24_3x
  FROM snap s LEFT JOIN ddp d ON d.mint = s.mint WHERE s.px_g240 > 0