"""Configuration loaded once from environment variables.

Pass A added Finnhub and HTTP fields; Pass B added the Telegram triple;
Pass C Step 0 added the tracked-tickers path; Pass C Step 9 adds the
Anthropic key + theses-doc path:

- NEWS_WATCH_DB_PATH               — required, absolute path to the SQLite database
- NEWS_WATCH_THEMES_DIR            — optional, directory of `*.yaml` theme files
                                      (default: `themes/` adjacent to the package)
- NEWS_WATCH_TRACKED_TICKERS_PATH  — optional, path to `tracked_tickers.yaml`
                                      (default: `config/tracked_tickers.yaml`
                                      adjacent to the package)
- NEWS_WATCH_BRIEF_ARCHIVE         — optional, default `~/.openclaw/news_watch/briefs`
- NEWS_WATCH_SYNTHESIS_CONFIG      — optional, path to `synthesis_config.yaml`
                                      (default: `config/synthesis_config.yaml`
                                      adjacent to the package)
- NEWS_WATCH_TRIGGER_LOG           — optional, default `~/.openclaw/news_watch/trigger_log.jsonl`
- NEWS_WATCH_PROPOSALS_PATH        — optional, default `~/.openclaw/news_watch/proposals/`.
                                      Holds pending.json (active drift proposals) and
                                      resolved.jsonl (append-only audit trail).
- NEWS_WATCH_THESES_PATH           — optional; absolute path to Abelard's THESES.md.
                                      Unset → synthesis runs the no-theses prompt
                                      variant and records a WARN in
                                      synthesis_metadata.theses_doc_warning.
- LOG_LEVEL                        — optional, default INFO
- FINNHUB_API_KEY                  — optional at load time; the Finnhub source plugin
                                      errors cleanly if missing at use time
- ANTHROPIC_API_KEY                — optional at load time; the synthesis layer
                                      errors cleanly at use time if missing
- NEWS_WATCH_USER_AGENT            — optional; default "news-watch-daemon/<version>"
- NEWS_WATCH_HTTP_TIMEOUT_S        — optional, default 10.0; positive float
- TELEGRAM_API_ID                  — optional; positive int if set (from my.telegram.org)
- TELEGRAM_API_HASH                — optional; 32-char lowercase hex if set
- TELEGRAM_SESSION_STRING          — optional; non-empty if set; generated by the
                                      one-time `python -m news_watch_daemon.telegram_setup`

The _RedactingFilter scrubs any secret returned by `secrets()` from log
output. FINNHUB_API_KEY, ANTHROPIC_API_KEY, TELEGRAM_API_HASH, and
TELEGRAM_SESSION_STRING join that set when present. TELEGRAM_API_ID is
not redacted — it's a numeric identifier publicly visible on the
my.telegram.org page.

Fails loudly on missing required values — the daemon should never start
with half-configuration.
"""

from __future__ import annotations

import logging
import os
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

from . import __version__


REDACTED = "***REDACTED***"

VALID_LOG_LEVELS = ("DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL")

DEFAULT_HTTP_TIMEOUT_S = 10.0
DEFAULT_USER_AGENT = f"news-watch-daemon/{__version__}"

# Telegram api_hash is a 32-char lowercase hex digest.
_TELEGRAM_API_HASH_RE = re.compile(r"^[0-9a-f]{32}$")


class ConfigError(RuntimeError):
    """Raised when required configuration is missing or invalid."""


def _default_themes_dir() -> Path:
    """Resolve `<repo_root>/themes` from this file's install location.

    Works for `pip install -e .` (editable). Non-editable installs
    should set NEWS_WATCH_THEMES_DIR explicitly.
    """
    return Path(__file__).resolve().parent.parent.parent / "themes"


def _default_tracked_tickers_path() -> Path:
    """Resolve `<repo_root>/config/tracked_tickers.yaml`.

    Mac mini deploy target reads from `~/.openclaw/news_watch/tracked_tickers.yaml`
    via the NEWS_WATCH_TRACKED_TICKERS_PATH env var.
    """
    return Path(__file__).resolve().parent.parent.parent / "config" / "tracked_tickers.yaml"


def _default_brief_archive_path() -> Path:
    """Resolve the default Brief archive path: `~/.openclaw/news_watch/briefs/`.

    Per Pass C §9. Override via NEWS_WATCH_BRIEF_ARCHIVE env var on
    the deploy target (Mac mini) or for tests.
    """
    return Path.home() / ".openclaw" / "news_watch" / "briefs"


def _default_synthesis_config_path() -> Path:
    """Resolve `<repo_root>/config/synthesis_config.yaml`.

    Mac mini deploy target reads from a workspace-local copy via
    NEWS_WATCH_SYNTHESIS_CONFIG; this bundled file is the daemon
    default + the source-of-truth for new installs.
    """
    return Path(__file__).resolve().parent.parent.parent / "config" / "synthesis_config.yaml"


def _default_trigger_log_path() -> Path:
    """Default append-only trigger log: `~/.openclaw/news_watch/trigger_log.jsonl`.

    Per Pass C §9. Append-only, never rotated — historical value
    compounds (calibration §14). Override via NEWS_WATCH_TRIGGER_LOG.
    """
    return Path.home() / ".openclaw" / "news_watch" / "trigger_log.jsonl"


def _default_proposals_path() -> Path:
    """Default drift-proposals directory: `~/.openclaw/news_watch/proposals/`.

    Pass C Step 11. Holds:
      - pending.json (active proposals, mutated by approve/reject)
      - resolved.jsonl (append-only audit trail, never rotated)

    Override via NEWS_WATCH_PROPOSALS_PATH on the deploy target.
    """
    return Path.home() / ".openclaw" / "news_watch" / "proposals"


@dataclass(frozen=True)
class Config:
    db_path: Path
    log_level: str
    themes_dir: Path = field(default_factory=_default_themes_dir)
    finnhub_api_key: str | None = None
    anthropic_api_key: str | None = None
    http_user_agent: str = DEFAULT_USER_AGENT
    http_default_timeout_s: float = DEFAULT_HTTP_TIMEOUT_S
    telegram_api_id: int | None = None
    telegram_api_hash: str | None = None
    telegram_session_string: str | None = None
    tracked_tickers_path: Path = field(default_factory=_default_tracked_tickers_path)
    brief_archive_path: Path = field(default_factory=_default_brief_archive_path)
    synthesis_config_path: Path = field(default_factory=_default_synthesis_config_path)
    trigger_log_path: Path = field(default_factory=_default_trigger_log_path)
    proposals_path: Path = field(default_factory=_default_proposals_path)
    theses_path: Path | None = None

    def secrets(self) -> tuple[str, ...]:
        """Values that must be scrubbed from log output.

        Currently: Finnhub API key, Anthropic API key, Telegram api_hash,
        Telegram session string. TELEGRAM_API_ID is not included — it is
        a numeric identifier publicly visible on my.telegram.org.
        """
        s: list[str] = []
        if self.finnhub_api_key:
            s.append(self.finnhub_api_key)
        if self.anthropic_api_key:
            s.append(self.anthropic_api_key)
        if self.telegram_api_hash:
            s.append(self.telegram_api_hash)
        if self.telegram_session_string:
            s.append(self.telegram_session_string)
        return tuple(s)

    @property
    def telegram_creds_complete(self) -> bool:
        """True iff all three Telegram credentials are present."""
        return (
            self.telegram_api_id is not None
            and bool(self.telegram_api_hash)
            and bool(self.telegram_session_string)
        )

    @classmethod
    def from_env(cls) -> "Config":
        raw_path = os.environ.get("NEWS_WATCH_DB_PATH", "").strip()
        if not raw_path:
            raise ConfigError(
                "NEWS_WATCH_DB_PATH is not set. Set to an absolute path to the "
                "SQLite database file (e.g. /tmp/news-watch.db)."
            )
        db_path = Path(raw_path).expanduser()
        if not db_path.is_absolute():
            raise ConfigError(
                f"NEWS_WATCH_DB_PATH must be an absolute path; got {raw_path!r}"
            )

        log_level = os.environ.get("LOG_LEVEL", "INFO").upper()
        if log_level not in VALID_LOG_LEVELS:
            raise ConfigError(
                f"LOG_LEVEL must be one of {VALID_LOG_LEVELS}; got {log_level!r}"
            )

        themes_raw = os.environ.get("NEWS_WATCH_THEMES_DIR", "").strip()
        if themes_raw:
            themes_dir = Path(themes_raw).expanduser()
            if not themes_dir.is_absolute():
                raise ConfigError(
                    f"NEWS_WATCH_THEMES_DIR must be an absolute path; got {themes_raw!r}"
                )
        else:
            themes_dir = _default_themes_dir()

        finnhub_key = os.environ.get("FINNHUB_API_KEY", "").strip() or None
        anthropic_key = os.environ.get("ANTHROPIC_API_KEY", "").strip() or None

        user_agent = os.environ.get("NEWS_WATCH_USER_AGENT", "").strip() or DEFAULT_USER_AGENT

        timeout_raw = os.environ.get("NEWS_WATCH_HTTP_TIMEOUT_S", "").strip()
        if timeout_raw:
            try:
                timeout = float(timeout_raw)
            except ValueError as exc:
                raise ConfigError(
                    f"NEWS_WATCH_HTTP_TIMEOUT_S must parse as a float; got {timeout_raw!r}"
                ) from exc
            if timeout <= 0:
                raise ConfigError(
                    f"NEWS_WATCH_HTTP_TIMEOUT_S must be positive; got {timeout}"
                )
        else:
            timeout = DEFAULT_HTTP_TIMEOUT_S

        # ---- Telegram (Pass B) ----

        tg_api_id_raw = os.environ.get("TELEGRAM_API_ID", "").strip()
        tg_api_id: int | None
        if tg_api_id_raw:
            try:
                tg_api_id = int(tg_api_id_raw)
            except ValueError as exc:
                raise ConfigError(
                    f"TELEGRAM_API_ID must parse as integer; got {tg_api_id_raw!r}"
                ) from exc
            if tg_api_id <= 0:
                raise ConfigError(
                    f"TELEGRAM_API_ID must be positive; got {tg_api_id}"
                )
        else:
            tg_api_id = None

        tg_api_hash_raw = os.environ.get("TELEGRAM_API_HASH", "").strip()
        tg_api_hash: str | None
        if tg_api_hash_raw:
            if not _TELEGRAM_API_HASH_RE.match(tg_api_hash_raw):
                raise ConfigError(
                    "TELEGRAM_API_HASH must be 32 lowercase hex characters; "
                    f"got {len(tg_api_hash_raw)}-char value"
                )
            tg_api_hash = tg_api_hash_raw
        else:
            tg_api_hash = None

        tg_session_raw = os.environ.get("TELEGRAM_SESSION_STRING", "").strip()
        tg_session: str | None = tg_session_raw if tg_session_raw else None

        # ---- Tracked tickers path (Pass C Step 0) ----

        tickers_raw = os.environ.get("NEWS_WATCH_TRACKED_TICKERS_PATH", "").strip()
        if tickers_raw:
            tickers_path = Path(tickers_raw).expanduser()
            if not tickers_path.is_absolute():
                raise ConfigError(
                    f"NEWS_WATCH_TRACKED_TICKERS_PATH must be an absolute path; got {tickers_raw!r}"
                )
        else:
            tickers_path = _default_tracked_tickers_path()

        # ---- Brief archive path (Pass C Step 2) ----

        archive_raw = os.environ.get("NEWS_WATCH_BRIEF_ARCHIVE", "").strip()
        if archive_raw:
            archive_path = Path(archive_raw).expanduser()
            if not archive_path.is_absolute():
                raise ConfigError(
                    f"NEWS_WATCH_BRIEF_ARCHIVE must be an absolute path; got {archive_raw!r}"
                )
        else:
            archive_path = _default_brief_archive_path()

        # ---- Synthesis config + trigger log paths (Pass C Step 4) ----

        synth_raw = os.environ.get("NEWS_WATCH_SYNTHESIS_CONFIG", "").strip()
        if synth_raw:
            synth_path = Path(synth_raw).expanduser()
            if not synth_path.is_absolute():
                raise ConfigError(
                    f"NEWS_WATCH_SYNTHESIS_CONFIG must be an absolute path; got {synth_raw!r}"
                )
        else:
            synth_path = _default_synthesis_config_path()

        trigger_raw = os.environ.get("NEWS_WATCH_TRIGGER_LOG", "").strip()
        if trigger_raw:
            trigger_path = Path(trigger_raw).expanduser()
            if not trigger_path.is_absolute():
                raise ConfigError(
                    f"NEWS_WATCH_TRIGGER_LOG must be an absolute path; got {trigger_raw!r}"
                )
        else:
            trigger_path = _default_trigger_log_path()

        # ---- Proposals directory (Pass C Step 11) ----

        proposals_raw = os.environ.get("NEWS_WATCH_PROPOSALS_PATH", "").strip()
        if proposals_raw:
            proposals_path = Path(proposals_raw).expanduser()
            if not proposals_path.is_absolute():
                raise ConfigError(
                    f"NEWS_WATCH_PROPOSALS_PATH must be an absolute path; got {proposals_raw!r}"
                )
        else:
            proposals_path = _default_proposals_path()

        # ---- Theses doc path (Pass C Step 9) ----
        # Unset is fine — synthesis runs the no-theses prompt variant and
        # records a WARN in synthesis_metadata.theses_doc_warning.
        theses_raw = os.environ.get("NEWS_WATCH_THESES_PATH", "").strip()
        theses_path: Path | None
        if theses_raw:
            theses_path = Path(theses_raw).expanduser()
            if not theses_path.is_absolute():
                raise ConfigError(
                    f"NEWS_WATCH_THESES_PATH must be an absolute path; got {theses_raw!r}"
                )
        else:
            theses_path = None

        return cls(
            db_path=db_path,
            log_level=log_level,
            themes_dir=themes_dir,
            finnhub_api_key=finnhub_key,
            anthropic_api_key=anthropic_key,
            http_user_agent=user_agent,
            http_default_timeout_s=timeout,
            telegram_api_id=tg_api_id,
            telegram_api_hash=tg_api_hash,
            telegram_session_string=tg_session,
            tracked_tickers_path=tickers_path,
            brief_archive_path=archive_path,
            synthesis_config_path=synth_path,
            trigger_log_path=trigger_path,
            proposals_path=proposals_path,
            theses_path=theses_path,
        )


class _RedactingFilter(logging.Filter):
    """Replace any occurrence of a known secret value with REDACTED.

    Belt-and-suspenders: source plugins should also scrub URL query params
    at emit time. This catches anything else that slips into a log record.
    """

    def __init__(self, secrets: tuple[str, ...]) -> None:
        super().__init__()
        self._secrets = tuple(s for s in secrets if s)

    def filter(self, record: logging.LogRecord) -> bool:
        if not self._secrets:
            return True
        msg = record.getMessage()
        redacted = msg
        for secret in self._secrets:
            if secret in redacted:
                redacted = redacted.replace(secret, REDACTED)
        if redacted != msg:
            record.msg = redacted
            record.args = ()
        return True


def configure_logging(config: Config) -> logging.Logger:
    """Configure the root daemon logger once. Logs to stderr. Idempotent."""
    logger = logging.getLogger("news_watch_daemon")
    logger.setLevel(config.log_level)
    if not any(isinstance(f, _RedactingFilter) for h in logger.handlers for f in h.filters):
        handler = logging.StreamHandler(stream=sys.stderr)
        handler.setFormatter(
            logging.Formatter("%(asctime)s %(levelname)s %(name)s: %(message)s")
        )
        handler.addFilter(_RedactingFilter(config.secrets()))
        logger.addHandler(handler)
    logger.propagate = False
    return logger
