"""Generate the tier-A pt_features query (burn-down item 3a, 2026-09-30).

Tier A = every column computable from swap events plus the create/complete/pool
events. The other columns (gate reconstructions, holder ledgers, funding joins,
clusters, organic v2) are emitted as typed NULLs here and measured separately
as unsaved runs, so each group's credit cost is attributable.

Writes three files under recon/sql/:
  pt_features_a_week.sql  - the 85-column table for one week of P graduates
                            (saved query + materialized view)
  pt_features_a_day.sql   - same logic, one graduation day, output summarised to
                            a handful of rows (validation; cheap to fetch)
Owner wallets never appear (public saved query). Public column names only.

State convention: event reserves are PRE-swap (validated, 1.6). The state at a
time T is the POST-swap state of the last event before T:
  buy : q_post = q + net_quote + lp_fee     b_post = b - base_out
  sell: q_post = q - quote_out + lp_fee     b_post = b + base_in
Price = (q + virtual_quote_reserves) / b; virtual = 0 pre-BOOST (this slice).
"""
import datetime as dt
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
SPEC = json.loads((ROOT / "recon" / "pt_features_schema.json").read_text(encoding="utf-8"))
WSOL = "So11111111111111111111111111111111111111112"
GS = (15, 60, 240)


def build(gd0: str, gd1: str) -> str:
    d0 = dt.date.fromisoformat(gd0)
    d1 = dt.date.fromisoformat(gd1)
    ev_end = (d1 + dt.timedelta(days=9)).isoformat()      # 7d window + 24h after g240 + margin
    cr_start = (d0 - dt.timedelta(days=70)).isoformat()   # creations up to 70d before graduation
    pool_end = (d1 + dt.timedelta(days=1)).isoformat()

    snap_g = ",\n".join(
        f"    max_by(px_post, t) FILTER (WHERE t < grad_time + INTERVAL '{g}' MINUTE) AS px_g{g},\n"
        f"    max_by(q_post,  t) FILTER (WHERE t < grad_time + INTERVAL '{g}' MINUTE) AS qres_g{g},\n"
        f"    max_by(b_post,  t) FILTER (WHERE t < grad_time + INTERVAL '{g}' MINUTE) AS bres_g{g},\n"
        f"    max(px_post) FILTER (WHERE t >= grad_time + INTERVAL '{g}' MINUTE AND t < grad_time + INTERVAL '7' DAY) AS peak_7d_g{g},\n"
        f"    max(px_post) FILTER (WHERE t >= grad_time + INTERVAL '{g}' MINUTE AND t < grad_time + INTERVAL '{g}' MINUTE + INTERVAL '24' HOUR) AS peak_24h_g{g}"
        for g in GS)
    snap_h = ",\n".join(
        f"    max_by(px_post, t) FILTER (WHERE t < grad_time + INTERVAL '{n}' {u}) AS px_{lab},\n"
        f"    max_by(q_post,  t) FILTER (WHERE t < grad_time + INTERVAL '{n}' {u}) AS qres_{lab}"
        for lab, n, u in (("1h", 1, "HOUR"), ("4h", 4, "HOUR"), ("24h", 24, "HOUR"), ("7d", 7, "DAY")))

    # Public names only; tier B/C columns are typed NULLs.
    tier_a = {
        "mint", "era", "stratum", "adm_src", "birth_proxy", "degraded", "pool", "quote_mint", "token_program",
        "create_time", "grad_time", "grad_slot", "creator", "vqr", "px_grad", "qres_grad",
        *[f"{p}_g{g}" for p in ("px", "qres", "bres", "peak_7d", "mdd_7d", "peak_24h", "mdd_24h", "mk") for g in GS],
        *[f"{p}_{h}" for p in ("px", "qres") for h in ("1h", "4h", "24h", "7d")],
        "c09a", "c09b", "c10", "adj_applied", "org1_n_7d", "org1_t_s",
        "cb_p50", "cs_p50", "cf_p50", "rs_p90", "n_7d", "qv_7d",
    }
    sel = []
    for col in SPEC["columns"]:
        p = col["public"]
        if p in tier_a:
            sel.append(f"  f.{p}")
        else:
            sel.append(f"  CAST(NULL AS {col['type']}) AS {p}")
    select_list = ",\n".join(sel)

    return f"""-- pt_features, tier A (event-derived), stratum P, graduations {gd0} .. {gd1}.
-- Generated by recon/gen_pt_features_tier_a.py. Public column names only; no owner wallets.
WITH comp AS (
  SELECT mint, evt_block_time AS ct
  FROM pumpdotfun_solana.pump_evt_completeevent
  WHERE evt_block_date BETWEEN DATE '{gd0}' AND DATE '{gd1}'),
pc AS (
  SELECT base_mint AS mint, pool, quote_mint, creator AS migrator, evt_block_time AS pt, evt_block_slot AS ps,
         row_number() OVER (PARTITION BY base_mint ORDER BY evt_block_time) AS rn
  FROM pumpdotfun_solana.pump_amm_evt_createpoolevent
  WHERE evt_block_date BETWEEN DATE '{gd0}' AND DATE '{pool_end}'),
u AS (
  SELECT c.mint, p.pool, p.quote_mint, p.migrator, p.pt AS grad_time, p.ps AS grad_slot
  FROM comp c JOIN pc p ON p.mint = c.mint AND p.rn = 1 AND p.pt >= c.ct AND p.pt < c.ct + INTERVAL '1' DAY
  WHERE p.quote_mint = '{WSOL}'),
cr AS (
  SELECT mint, arbitrary(creator) AS creator, min(evt_block_time) AS create_time, arbitrary(token_program) AS token_program
  FROM pumpdotfun_solana.pump_evt_createevent
  WHERE evt_block_date BETWEEN DATE '{cr_start}' AND DATE '{gd1}' AND mint IN (SELECT mint FROM u)
  GROUP BY 1),
ev AS (
  SELECT pool, evt_block_time AS t, evt_block_slot AS slot, 'buy' AS side, user AS w,
         CAST(pool_quote_token_reserves AS double) AS q, CAST(pool_base_token_reserves AS double) AS b,
         CASE WHEN ix_name = 'buy_exact_quote_in' THEN CAST(quote_amount_in AS double) ELSE CAST(user_quote_amount_in AS double) END AS gross,
         CASE WHEN ix_name = 'buy_exact_quote_in' THEN CAST(user_quote_amount_in AS double) ELSE CAST(quote_amount_in AS double) END AS net,
         CAST(base_amount_out AS double) AS base_amt, CAST(lp_fee AS double) AS lp,
         CAST(protocol_fee AS double) AS prot, CAST(coin_creator_fee AS double) AS cre
  FROM pumpdotfun_solana.pump_amm_evt_buyevent
  WHERE evt_block_date BETWEEN DATE '{gd0}' AND DATE '{ev_end}' AND pool IN (SELECT pool FROM u)
  UNION ALL
  SELECT pool, evt_block_time, evt_block_slot, 'sell', user,
         CAST(pool_quote_token_reserves AS double), CAST(pool_base_token_reserves AS double),
         CAST(quote_amount_out AS double), CAST(user_quote_amount_out AS double),
         CAST(base_amount_in AS double), CAST(lp_fee AS double), CAST(protocol_fee AS double), CAST(coin_creator_fee AS double)
  FROM pumpdotfun_solana.pump_amm_evt_sellevent
  WHERE evt_block_date BETWEEN DATE '{gd0}' AND DATE '{ev_end}' AND pool IN (SELECT pool FROM u)),
e AS (
  SELECT u.mint, u.grad_time, u.grad_slot, u.migrator, cr.creator, ev.*,
         CASE WHEN ev.side = 'buy' THEN ev.q + ev.net + ev.lp ELSE ev.q - ev.gross + ev.lp END AS q_post,
         CASE WHEN ev.side = 'buy' THEN ev.b - ev.base_amt ELSE ev.b + ev.base_amt END AS b_post
  FROM ev JOIN u ON u.pool = ev.pool
  LEFT JOIN cr ON cr.mint = u.mint
  WHERE ev.t >= u.grad_time AND ev.t < u.grad_time + INTERVAL '8' DAY),
ep AS (
  SELECT *, q / NULLIF(b, 0) AS px_pre, q_post / NULLIF(b_post, 0) AS px_post FROM e),
snap AS (
  SELECT mint, grad_time,
    min_by(px_pre, t) AS px_grad, min_by(q, t) AS qres_grad,
{snap_g},
{snap_h},
    approx_percentile(1e4 * (gross - net) / gross, 0.5) FILTER (WHERE side = 'buy'  AND gross > 0 AND t < grad_time + INTERVAL '7' DAY) AS cb_p50,
    approx_percentile(1e4 * (gross - net) / gross, 0.5) FILTER (WHERE side = 'sell' AND gross > 0 AND t < grad_time + INTERVAL '7' DAY) AS cs_p50,
    approx_percentile(1e4 * cre / gross, 0.5) FILTER (WHERE gross > 0 AND t < grad_time + INTERVAL '7' DAY) AS cf_p50,
    approx_percentile(1e4 * (gross - net - lp - prot - coalesce(cre, 0)) / gross, 0.9) FILTER (WHERE gross > 0 AND t < grad_time + INTERVAL '7' DAY) AS rs_p90,
    count_if(t < grad_time + INTERVAL '7' DAY) AS n_7d,
    sum(gross) FILTER (WHERE t < grad_time + INTERVAL '7' DAY) AS qv_7d,
    bool_or(side = 'sell' AND t < grad_time + INTERVAL '30' MINUTE AND w <> migrator AND (creator IS NULL OR w <> creator)) AS c10
  FROM ep GROUP BY 1, 2),
dd AS (   -- max drawdown per G and window, via running max over the window
  SELECT mint, g, win, max(1 - px_post / runmax) AS mdd FROM (
    SELECT ep.mint, gw.g, gw.win, ep.px_post,
           max(ep.px_post) OVER (PARTITION BY ep.mint, gw.g, gw.win ORDER BY ep.t, ep.slot ROWS UNBOUNDED PRECEDING) AS runmax
    FROM ep CROSS JOIN (VALUES (15, '24h'), (60, '24h'), (240, '24h'), (15, '7d'), (60, '7d'), (240, '7d')) AS gw(g, win)
    WHERE ep.t >= ep.grad_time + gw.g * INTERVAL '1' MINUTE
      AND ep.t < CASE WHEN gw.win = '24h' THEN ep.grad_time + gw.g * INTERVAL '1' MINUTE + INTERVAL '24' HOUR
                      ELSE ep.grad_time + INTERVAL '7' DAY END
  ) x GROUP BY 1, 2, 3),
ddp AS (
  SELECT mint,
    max(mdd) FILTER (WHERE g = 15  AND win = '7d')  AS mdd_7d_g15,
    max(mdd) FILTER (WHERE g = 60  AND win = '7d')  AS mdd_7d_g60,
    max(mdd) FILTER (WHERE g = 240 AND win = '7d')  AS mdd_7d_g240,
    max(mdd) FILTER (WHERE g = 15  AND win = '24h') AS mdd_24h_g15,
    max(mdd) FILTER (WHERE g = 60  AND win = '24h') AS mdd_24h_g60,
    max(mdd) FILTER (WHERE g = 240 AND win = '24h') AS mdd_24h_g240
  FROM dd GROUP BY 1),
d24 AS (  -- c09a / c09b: first 24h volume and same-wallet round trips
  SELECT mint, sum(vol) / NULLIF(count(*), 0) / 1e9 AS c09a,
         sum(CASE WHEN has_b AND has_s THEN vol END) / NULLIF(sum(vol), 0) AS c09b
  FROM (SELECT mint, w, sum(gross) AS vol, bool_or(side = 'buy') AS has_b, bool_or(side = 'sell') AS has_s
        FROM ep WHERE t < grad_time + INTERVAL '24' HOUR GROUP BY 1, 2) GROUP BY 1),
org AS (  -- organic v1: not creator, not migrator, not a graduation-slot trader
  SELECT ep.mint, count(DISTINCT ep.w) AS org1_n_7d, date_diff('second', min(ep.grad_time), min(ep.t)) AS org1_t_s
  FROM ep
  WHERE ep.t < ep.grad_time + INTERVAL '7' DAY AND ep.w <> ep.migrator AND (ep.creator IS NULL OR ep.w <> ep.creator)
    AND NOT EXISTS (SELECT 1 FROM ep b WHERE b.mint = ep.mint AND b.slot = b.grad_slot AND b.w = ep.w)
  GROUP BY 1),
f AS (
  SELECT u.mint,
    CASE WHEN u.grad_time < TIMESTAMP '2026-07-21 00:00:00' THEN 'pre_boost' ELSE 'post_boost' END AS era,
    'P' AS stratum, 'complete_to_pool_1d' AS adm_src, false AS birth_proxy,
    CAST(u.grad_time AS date) BETWEEN DATE '2025-08-05' AND DATE '2025-08-11' AS degraded,
    u.pool, u.quote_mint, cr.token_program, cr.create_time, u.grad_time, u.grad_slot, cr.creator,
    CAST(0 AS double) AS vqr,
    s.px_grad, s.qres_grad,
    s.px_g15, s.px_g60, s.px_g240, s.qres_g15, s.qres_g60, s.qres_g240, s.bres_g15, s.bres_g60, s.bres_g240,
    s.px_1h, s.px_4h, s.px_24h, s.px_7d, s.qres_1h, s.qres_4h, s.qres_24h, s.qres_7d,
    s.peak_7d_g15, s.peak_7d_g60, s.peak_7d_g240, s.peak_24h_g15, s.peak_24h_g60, s.peak_24h_g240,
    d.mdd_7d_g15, d.mdd_7d_g60, d.mdd_7d_g240, d.mdd_24h_g15, d.mdd_24h_g60, d.mdd_24h_g240,
    v.c09a, v.c09b, s.c10, false AS adj_applied, o.org1_n_7d, o.org1_t_s,
    s.cb_p50, s.cs_p50, s.cf_p50, s.rs_p90,
    s.px_g15 / NULLIF(s.px_grad, 0) AS mk_g15, s.px_g60 / NULLIF(s.px_grad, 0) AS mk_g60, s.px_g240 / NULLIF(s.px_grad, 0) AS mk_g240,
    s.n_7d, s.qv_7d
  FROM u LEFT JOIN cr ON cr.mint = u.mint LEFT JOIN snap s ON s.mint = u.mint
  LEFT JOIN ddp d ON d.mint = u.mint LEFT JOIN d24 v ON v.mint = u.mint LEFT JOIN org o ON o.mint = u.mint)
SELECT
{select_list}
FROM f"""


def main() -> None:
    week = build("2025-06-09", "2025-06-15")
    day = build("2025-06-09", "2025-06-09")
    day_summary = (day.replace("SELECT\n  f.mint,", "SELECT\n  f.mint AS mint_,", 1)
                   if False else day)
    # Day validation: wrap the 85-column result in a summary so the fetch is a few rows.
    summary = f"""WITH t AS (
{day}
)
SELECT count(*) AS tokens,
       count(px_grad) AS has_px_grad, count(px_g240) AS has_px_g240, count(px_7d) AS has_px_7d,
       count(create_time) AS has_create, count(mdd_7d_g15) AS has_mdd,
       approx_percentile(mk_g15, 0.5) AS mk_g15_p50, approx_percentile(mk_g240, 0.5) AS mk_g240_p50,
       approx_percentile(qres_7d / NULLIF(qres_grad, 0), 0.5) AS reserve_ratio_7d_p50,
       approx_percentile(mdd_7d_g15, 0.5) AS mdd_7d_g15_p50, approx_percentile(peak_24h_g15 / NULLIF(px_g15, 0), 0.5) AS peak24_over_entry_p50,
       approx_percentile(cb_p50, 0.5) AS cb_p50_p50, approx_percentile(org1_n_7d, 0.5) AS org1_p50,
       count_if(c10) AS c10_true, count(token_program) AS has_token_program, count(qres_g15) AS has_qres_g15
FROM t"""
    out = ROOT / "recon" / "sql"
    (out / "pt_features_a_week.sql").write_text(week, encoding="utf-8")
    (out / "pt_features_a_day.sql").write_text(summary, encoding="utf-8")
    print("written: pt_features_a_week.sql, pt_features_a_day.sql (summary)")


if __name__ == "__main__":
    main()
